const mongoose = require("mongoose");
const Schema = mongoose.Schema;
const specReqString = { type: String, default: "" };

const teamSchema = new Schema(
    {
<<<<<<< Updated upstream
        creativeparticipant1: specReqString,
        creativeparticipant2: specReqString,
        creativeparticipant3: specReqString,
        creativeparticipant4: specReqString,
        creativeparticipant5: specReqString,
        creativeparticipant6: specReqString,
        crossparticipant1: specReqString,
        crossparticipant2: specReqString,
        gdparticipant1: specReqString,
        surpparticipant1: specReqString,
        surpparticipant2: specReqString,
        progparticipant1: specReqString,
        progparticipant2: specReqString,
        filmparticipant1: specReqString,
        filmparticipant2: specReqString,
        filmparticipant3: specReqString,
        filmparticipant4: specReqString,
        gamingparticipant1: specReqString,
        gamingparticipant2: specReqString,
        quizparticipant1: specReqString,
        roboticsparticipant1: specReqString,
        roboticsparticipant2: specReqString,
        roboticsparticipant3: specReqString,
        photoparticipant1: specReqString,
        paintparticipant1: specReqString,
        gamedevparticipant1: specReqString,
        gamedevparticipant2: specReqString,
        minecraftparticipant1: specReqString,
        minecraftparticipant2: specReqString,
=======
        schId: nonReqString,
        schName: nonReqString,
        creativeparticipant1: nonReqString,
        creativeparticipant2: nonReqString,
        creativeparticipant3: nonReqString,
        creativeparticipant4: nonReqString,
        creativeparticipant5: nonReqString,
        creativeparticipant6: nonReqString,
        crossparticipant1: nonReqString,
        crossparticipant2: nonReqString,
        gdparticipant1: nonReqString,
        surpparticipant1: nonReqString,
        surpparticipant2: nonReqString,
        progparticipant1: nonReqString,
        progparticipant2: nonReqString,
        filmparticipant1: nonReqString,
        filmparticipant2: nonReqString,
        filmparticipant3: nonReqString,
        filmparticipant4: nonReqString,
        gamingparticipant1: nonReqString,
        gamingparticipant2: nonReqString,
        quizparticipant1: nonReqString,
        roboticsparticipant1: nonReqString,
        roboticsparticipant2: nonReqString,
        roboticsparticipant3: nonReqString,
        photoparticipant1: nonReqString,
        paintparticipant1: nonReqString,
        gamedevparticipant1: nonReqString,
        gamedevparticipant2: nonReqString,
        minecraftparticipant1: nonReqString,
        minecraftparticipant2: nonReqString,
>>>>>>> Stashed changes
    },
    { timestamps: true }
);

module.exports = mongoose.model("Team", teamSchema);